// Create diary for each player
_null = player createDiaryRecord ["Diary", [localize "str_a3_diary_execution_title", format ["%1%4%2%4%3",localize "STR_A3_EscapeFromTanoa_execution01",format [localize "STR_A3_EscapeFromMalden_execution02","</marker>", "<marker name = 'BIS_mrkAirbase'>","<marker name = 'BIS_mrkBase'>"],localize "STR_A3_EscapeFromTanoa_execution03","<br /><br />"]]];

// Add respawn tickets if set to individual unit
if (missionNamespace getVariable "BIS_respawnTickets" == 0) then {[player,1] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 1) then {[player,2] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 2) then {[player,3] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 3) then {[player,4] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 4) then {[player,5] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 5) then {[player,6] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 6) then {[player,10] call BIS_fnc_respawnTickets};

// Handle JIP respawn
missionNamespace setVariable ["_initialRespawn", addMissionEventHandler ["PreloadFinished",
{
	removeMissionEventHandler ["PreloadFinished", missionNamespace getVariable ["_initialRespawn", -1]];
	missionNamespace setVariable ["_initialRespawn", nil];

	if (didJIP and (time > 30)) then
	{
		player enableSimulationGlobal false;
		player enableSimulation false;
		player hideObjectGlobal true;
		player hideObject true;
		forceRespawn player;
		deleteVehicle player;
	};
}]];

// Set available loadout
if (typeOf player == "O_Soldier_SL_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"O_SquadLeader"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","acc_pointer_IR","optic_Arco_blk_F",["30Rnd_65x39_caseless_green_mag_Tracer",30],[],""],[],["hgun_Pistol_heavy_02_F","","","",["6Rnd_45ACP_Cylinder",6],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["6Rnd_45ACP_Cylinder",2,6]]],["V_TacVest_khk",[["30Rnd_65x39_caseless_green_mag_Tracer",7,30],["HandGrenade",2,1]]],[],"H_HelmetLeaderO_ocamo",nil,["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 1) then {[player,"O_SquadLeader_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","","optic_Arco_blk_F",["30Rnd_65x39_caseless_green_mag_Tracer",30],[],""],[],["hgun_Pistol_heavy_02_F","","","",["6Rnd_45ACP_Cylinder",6],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["6Rnd_45ACP_Cylinder",2,6]]],["V_TacVest_khk",[["30Rnd_65x39_caseless_green_mag_Tracer",3,30],["HandGrenade",2,1]]],[],"H_HelmetLeaderO_ocamo",nil,["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 2) then {[player,"O_SquadLeader_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","","",["30Rnd_65x39_caseless_green_mag_Tracer",30],[],""],[],["hgun_Pistol_heavy_02_F","","","",["6Rnd_45ACP_Cylinder",6],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["6Rnd_45ACP_Cylinder",2,6]]],["V_TacVest_khk",[["30Rnd_65x39_caseless_green_mag_Tracer",1,30],["HandGrenade",2,1]]],[],"H_HelmetLeaderO_ocamo",nil,["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
};

if (typeOf player == "O_soldier_M_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"O_Marksman"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["srifle_DMR_01_F","","","optic_dms",["10Rnd_762x54_Mag",10],[],"bipod_02_F_blk"],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["10Rnd_762x54_Mag",11,10],["HandGrenade",2,1]]],[],"H_HelmetSpecO_ocamo",nil,["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 1) then {[player,"O_Marksman_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["srifle_DMR_01_F","","","optic_dms",["10Rnd_762x54_Mag",10],[],"bipod_02_F_blk"],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["10Rnd_762x54_Mag",5,10],["HandGrenade",2,1]]],[],"H_HelmetSpecO_ocamo",nil,["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 2) then {[player,"O_Marksman_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["srifle_DMR_01_F","","","",["10Rnd_762x54_Mag",10],[],"bipod_02_F_blk"],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["10Rnd_762x54_Mag",2,10],["HandGrenade",2,1]]],[],"H_HelmetSpecO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
};

if (typeOf player == "O_soldier_AR_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"O_Autorifleman"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["LMG_Zafir_F","","acc_pointer_IR","",["150Rnd_762x54_Box",150],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["150Rnd_762x54_Box",2,150],["HandGrenade",2,1]]],[],"H_HelmetO_ocamo",nil,[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 1) then {[player,"O_Autorifleman_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["LMG_Zafir_F","","","",["150Rnd_762x54_Box",150],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["150Rnd_762x54_Box",1,150],["HandGrenade",2,1]]],[],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 2) then {[player,"O_Autorifleman_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["LMG_Zafir_F","","","",["150Rnd_762x54_Box",150],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["HandGrenade",2,1]]],[],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
};

if (typeOf player == "O_soldier_GL_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"O_Grenadier"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_GL_F","","acc_pointer_IR","optic_ACO_grn",["30Rnd_65x39_caseless_green",30],["1Rnd_HE_Grenade_shell",1],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessOGL_brn",[["30Rnd_65x39_caseless_green",7,30],["HandGrenade",2,1],["1Rnd_HE_Grenade_shell",5,1]]],[],"H_HelmetO_ocamo",nil,[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 1) then {[player,"O_Grenadier_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_GL_F","","","optic_ACO_grn",["30Rnd_65x39_caseless_green",30],["1Rnd_HE_Grenade_shell",1],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessOGL_brn",[["30Rnd_65x39_caseless_green",3,30],["HandGrenade",2,1],["1Rnd_HE_Grenade_shell",3,1]]],[],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 2) then {[player,"O_Grenadier_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_GL_F","","","",["30Rnd_65x39_caseless_green",30],["1Rnd_HE_Grenade_shell",1],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessOGL_brn",[["30Rnd_65x39_caseless_green",1,30],["HandGrenade",2,1],["1Rnd_HE_Grenade_shell",1,1]]],[],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
};

if (typeOf player == "O_soldier_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"O_Rifleman"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","acc_pointer_IR","optic_ACO_grn",["30Rnd_65x39_caseless_green",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["30Rnd_65x39_caseless_green",7,30],["HandGrenade",2,1]]],[],"H_HelmetO_ocamo",nil,[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 1) then {[player,"O_Rifleman_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","","optic_ACO_grn",["30Rnd_65x39_caseless_green",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["30Rnd_65x39_caseless_green",3,30],["HandGrenade",2,1]]],[],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 2) then {[player,"O_Rifleman_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","","",["30Rnd_65x39_caseless_green",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["30Rnd_65x39_caseless_green",1,30],["HandGrenade",2,1]]],[],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
};

if (typeOf player == "O_soldier_LAT_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"O_AT"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","acc_pointer_IR","optic_ACO_grn",["30Rnd_65x39_caseless_green",30],[],""],["launch_RPG32_F","","","",["RPG32_F",1],[],""],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["16Rnd_9x21_Mag",2,16],["SmokeShell",2,1]]],["V_HarnessO_brn",[["30Rnd_65x39_caseless_green",7,30],["HandGrenade",2,1]]],["B_FieldPack_ocamo",[["RPG32_F",1,1],["RPG32_HE_F",1,1]]],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 1) then {[player,"O_AT_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","","optic_ACO_grn",["30Rnd_65x39_caseless_green",30],[],""],["launch_RPG32_F","","","",["RPG32_F",1],[],""],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["16Rnd_9x21_Mag",2,16],["SmokeShell",2,1]]],["V_HarnessO_brn",[["30Rnd_65x39_caseless_green",3,30],["HandGrenade",2,1]]],["B_FieldPack_ocamo",[["RPG32_F",1,1],["RPG32_HE_F",1,1]]],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 2) then {[player,"O_AT_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","","",["30Rnd_65x39_caseless_green",30],[],""],["launch_RPG32_F","","","",["RPG32_F",1],[],""],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["16Rnd_9x21_Mag",2,16],["SmokeShell",2,1]]],["V_HarnessO_brn",[["30Rnd_65x39_caseless_green",1,30],["HandGrenade",2,1]]],["B_FieldPack_ocamo",[["RPG32_F",1,1],["RPG32_HE_F",1,1]]],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
};

if (typeOf player == "O_engineer_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"O_Engineer"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","acc_pointer_IR","optic_ACO_grn",["30Rnd_65x39_caseless_green",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["30Rnd_65x39_caseless_green",7,30]]],["B_AssaultPack_ocamo",[["ToolKit",1],["MineDetector",1],["DemoCharge_Remote_Mag",2,1]]],"H_HelmetO_ocamo",nil,[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 1) then {[player,"O_Engineer_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","","optic_ACO_grn",["30Rnd_65x39_caseless_green",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["30Rnd_65x39_caseless_green",3,30]]],["B_AssaultPack_ocamo",[["ToolKit",1],["MineDetector",1],["DemoCharge_Remote_Mag",2,1]]],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 2) then {[player,"O_Engineer_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","","",["30Rnd_65x39_caseless_green",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_HarnessO_brn",[["30Rnd_65x39_caseless_green",1,30]]],["B_AssaultPack_ocamo",[["ToolKit",1],["MineDetector",1],["DemoCharge_Remote_Mag",2,1]]],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
};

if (typeOf player == "O_medic_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"O_CombatLifesaver"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","acc_pointer_IR","optic_ACO_grn",["30Rnd_65x39_caseless_green",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShellRed",4,1],["16Rnd_9x21_Mag",2,16]]],["V_TacVest_khk",[["30Rnd_65x39_caseless_green",7,30]]],["B_AssaultPack_ocamo",[["Medikit",1]]],"H_HelmetO_ocamo",nil,[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 1) then {[player,"O_CombatLifesaver_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","","optic_ACO_grn",["30Rnd_65x39_caseless_green",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShellRed",4,1],["16Rnd_9x21_Mag",2,16]]],["V_TacVest_khk",[["30Rnd_65x39_caseless_green",3,30]]],["B_AssaultPack_ocamo",[["Medikit",1]]],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
	if (BIS_loadoutLevel == 2) then {[player,"O_CombatLifesaver_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_Katiba_F","","","",["30Rnd_65x39_caseless_green",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_O_CombatUniform_ocamo",[["FirstAidKit",1],["SmokeShellRed",4,1],["16Rnd_9x21_Mag",2,16]]],["V_TacVest_khk",[["30Rnd_65x39_caseless_green",1,30]]],["B_AssaultPack_ocamo",[["Medikit",1]]],"H_HelmetO_ocamo",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"]]};
};
