_r = ([] CALL AllPf) call RETURNRANDOM;
_r action ["lightOn", _this]; 
sleep 0.5;
_r action ["lightOff", _this]; 
sleep 0.5;
_r action ["lightOff", _this]; 
sleep 0.5;
_r action ["lightOff", _this]; 
sleep 0.5;
_r action ["lightOff", _this]; 
sleep 0.5;
_r action ["lightOff", _this]; 
sleep 0.5;
_r action ["lightOff", _this]; 
sleep 0.5;
_r action ["lightOff", _this]; 
sleep 0.5;