private ["_group", "_xx", "_yy", "_end"];
_group = _this select 0;
_xx = random (1100);
_yy = 1100 - _xx;
if (random 1 < 0.5) then {_xx = _xx*(-1)};
_yy = _yy*(-1);
_uu = (([] CALL AllPf) call RETURNRANDOM);
_end = [(getposATL _uu select 0) + _xx,(getposATL _uu select 1) + _yy,0];
while  {surfaceIsWater [_end select 0, _end select 1]} do {
sleep 1;
_xx = random (1100);
_yy = 1100 - _xx;
if (random 1 < 0.5) then {_xx = _xx*(-1)};
_yy = _yy*(-1);
_uu = (([] CALL AllPf) call RETURNRANDOM);
_end = [(getposATL _uu select 0) + _xx,(getposATL _uu select 1) + _yy,0];
};
_group move _end;
waituntil {sleep 20; {leader _group distance _x < 300} count ([] CALL AllPf) == 0};
{deletevehicle _x;} foreach units _group;