private ["_veh","_way","_pos","_xx","_yy","_start","_wp1","_pPos"];
//if (true) exitWith {};
_n = ("vehStuc") SPAWN DiagForCPS;
_veh = _this select 0;
_way = _this select 1;
_pos = + (getposATL _veh);
sleep 30;
while {!isNull _veh && {_pos distance (getposATL _veh) < 15} && {(vehicle _x) distance _veh < 400} count ([] CALL AllPf) == 0} do {
_xx = random (1100);
_yy = 1100 - _xx;
if (random 1 < 0.5) then {_xx = _xx*(-1)};
if (random 1 < 0.5) then {_yy = _yy*(-1)};
_pPos = getposATL (([] CALL AllPf) call RETURNRANDOM);
_start = [(_pPos select 0) + _xx,(_pPos select 1) + _yy,0];
while  {!isNull _veh && {surfaceIsWater _start}} do {
sleep 5;
_xx = random 1100;
_yy = 1100 - _xx;
if (random 1 < 0.5) then {_xx = _xx*(-1)};
if (random 1 < 0.5) then {_yy = _yy*(-1)};
_pPos = getposATL (([] CALL AllPf) call RETURNRANDOM);
_start = [(_pPos select 0) + _xx,(_pPos select 1) + _yy,0];
};
_veh setpos _start;
while {!isNull _veh && {(count (waypoints (group driver _veh))) > 0}} do {deleteWaypoint ((waypoints (group driver _veh)) select 0);};
_wp1= (group driver _veh) addWaypoint [_way, 0]; 
[(group driver _veh), 1] setWaypointBehaviour "COMBAT";
_pos = + (getposATL _veh);
sleep 30;
_pos = + (getposATL _veh);
};